# -*- coding: utf-8 -*-
"""Temp_Moisture_Data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EanOsJUK34KhgTqjTNtDxmsJFFahX-l-

## Importing the libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""## Importing the dataset"""

dataset = pd.read_csv('temp_moisture_data.csv')

dataset.head()
print(dataset.columns)
dataset.info()

dataset['Date'] = pd.to_datetime(dataset['Date'])
dataset['month'] = dataset['Date'].dt.month
dataset['year'] = dataset['Date'].dt.year
dataset

import seaborn as sns
sns.set(rc = {'figure.figsize' : (14,12)})
sns.heatmap(dataset.corr().round(2) , annot = True )

"""##Removing Variables from Dataset

"""

dataset = dataset.drop(columns="Date")
dataset

X = np.array(dataset.iloc[ : , 0 : 5].values)
y = dataset.iloc[:, 1].values

"""##Splitting data into Training and Testing"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""##*Training the Multiple Linear Regression model on the Training set*"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

"""## Predicting and Evaluating the Test set results"""

y_pred = regressor.predict(X_test)
print("R-Squared of Training Data is:",regressor.score(X_train, y_train))
print("R-Squared of Test Data is:",regressor.score(X_test, y_test))

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(regressor,X_train,y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))